version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
            sh -c "./test.sh &&
            python -m flask run --host=0.0.0.0"
    ports:
      - "8000:5000"